config/routes.rb
Rails.application.routes.draw do

  resources :task_logs

  resources :tasks do
    member do
      get :sms
      get :empty_log
    end
  end

  post 'twilio/sms' => 'twilio#sms'
  post 'twilio/status' => 'twilio#status'

  root :to => "tasks#index"

end

app/models/task.rb
class Task < ActiveRecord::Base

  has_many :task_logs

  validates :deadline, :presence => true
  validates :assigned_name, :presence => true
  validates :assigned_phone, :presence => true
  validates :state, :presence => true

  before_create :build_initial_log
  after_save :log_state

=begin
  state_machine :state, :initial => :pending do
    #twilio states: pending, sent, delivered, failed or undelivered

    after_transition :to => all do |task, transition|
      task.task_logs.create(:state => task.state)
    end

    event :queue_sms do
      transition all => :sms_queued
    end

    event :send_sms do
      transition all => :sms_sent
    end

    event :fail_sms do
      transition all => :sms_failed
    end

    event :accept do
      transition all => :accepted
    end

    event :reject do
      transition all => :rejected
    end

    event :complete do
      transition all => :completed
    end
  end
=end

  private

    def build_initial_log
      self.task_logs.build(:state => self.state)
    end

    def log_state
      if self.state_changed? or self.last_message_sid_changed? or self.last_message_state_changed? or self.last_message_changed?
        message = self.last_message_sid_changed? ? self.last_message : ""
        message_state = self.last_message_state_changed? ? self.last_message_state : ""
        self.task_logs.create(:state => self.state, :message_state => message_state, :message => message)
      end
    end

end

app/models/task_log.rb
class TaskLog < ActiveRecord::Base
  belongs_to :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/webhookable.rb
module Webhookable extend ActiveSupport::Concern
 
  def set_header
    response.headers["Content-Type"] = "text/xml"
  end
 
  def render_twiml(response)
    render text: response.text
  end
 
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_task, only: [:show, :edit, :update, :destroy, :sms, :empty_log]

  # GET /tasks
  def index
    @tasks = Task.all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  def create
    @task = Task.new(task_params)

    if @task.save
      respond_to do |format|
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created }
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  def update
    if @task.update(task_params)
      respond_to do |format|
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render json: @task, status: :ok }
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /tasks/1/sms
  def sms
    # twilio account settings: this should go somewhere else, like configatron variables
    twilio_endpoint = "https://api.twilio.com/2008-08-01"
    twilio_accountSid = "ACf143846021ae6e180b73c4bebfc4d2e0"
    twilio_authToken = "faf73f854fca4922d4cb1f9206e0c4fc"
    twilio_phoneNumber = "+14244880161"

    number_to_send_to = @task.assigned_phone

    @twilio_client = Twilio::REST::Client.new twilio_accountSid, twilio_authToken
    body = "Hello #{@task.assigned_name}, are you able for a task on #{I18n.l(@task.deadline)}?"

    # the sending of the message should be done through a delayed job so that the application doesn't hang if the twilio api takes too long
    @sms = @twilio_client.account.sms.messages.create(
      :from => twilio_phoneNumber,
      :to => number_to_send_to,
      :body => body,
      :StatusCallback => twilio_status_url(:task_id => @task.id)
    )

    @task.update_attributes(:state => "waiting_response", :last_message => body, :last_message_sid => '')
    respond_to do |format|
      format.html { redirect_to @task, notice: 'The SMS was sent.' }
      format.json { render json: @task, status: :ok }
    end

  end

  def empty_log
    @task.task_logs.destroy_all
    respond_to do |format|
      format.html { redirect_to @task, notice: 'Task log was successfully cleaned.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:deadline, :assigned_name, :assigned_phone, :state)
    end
end

app/controllers/twilio_controller.rb
require 'twilio-ruby'
 
class TwilioController < ApplicationController
  include Webhookable
  skip_before_action :verify_authenticity_token
 
  after_filter :set_header
 
  skip_before_action :verify_authenticity_token
 
  def sms
    tasks = Task.where(:assigned_phone => params['From'])
    if tasks.any?
      @task = tasks.last
      state = @task.state

      body = params['Body']
      if body.start_with?("Sent from your Twilio trial account - ")
        body = body["Sent from your Twilio trial account - ".length,body.length]
      end

      if @task.state == 'waiting_response'
        state = 'conversation'
      end

      response_message = ''
      if @task.state == 'waiting_response' or @task.state == 'conversation'
        if ["si", "ok", "de acuerdo", "d'acord", "good"].include?(body.downcase)
          state = 'accepted'
          response_message = 'OK, pues ya me avisaras si hay algun problema'
        elsif ["no", "no puedo"].include?(body.downcase)
          state = 'rejected'
          response_message = 'OK, ya buscare a alguien'
        end
      end
      @task.update_attributes(:state => state, :last_message => body, :last_message_state => params['SmsStatus'], :last_message_sid => params['SmsSid'])
    end

    if response_message.blank?
      response = Twilio::TwiML::Response.new do |r|
      end
    else
      response = Twilio::TwiML::Response.new do |r|
        r.Message response_message
      end
      # save a random sid so that the model knows it must create a new log for this task
      sid = (0...10).map { ('a'..'z').to_a[rand(26)] }.join
      @task.update_attributes(:last_message => response_message, :last_message_sid => sid)
    end

    render_twiml response
  end

  def status
    @task = Task.find(params[:task_id])
    @task.update_attributes(:last_message_state => params['SmsStatus'], :last_message_sid => params['SmsSid'])
   
    # send back an empty response
    render_twiml Twilio::TwiML::Response.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_logs_helper.rb
module TaskLogsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VrEasy</title>
    <link rel="icon" href="/favicon.ico" type="image/png">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar"
            data-toggle="collapse"
            data-target=".nav-collapse">
                <span class="icon-bar"></span>
          </a>
          <a class="brand"
            href="/">
                <img src="/assets/vreasy-logotype-dark.png" title="VrEasy">
          </a>
          <div class="nav-collapse collapse">
            <ul class="nav">
                <li>
                    <a href="/tasks">Tasks</a>
                </li>
            </ul>
            <ul class="nav pull-right">
                <li>
                    <a href="#">Property Manager</a>
                </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="container"
        id="vreasy-main-container"
        style="position: relative;">
      <%= yield %>
    </div>
    <hr>
    <div class="container">
      <footer>
        <p class="ar copyright pull-right">
            <small>
              &copy; VrEasy &trade;
            </small>
        </p>
      </footer>
   </div>

  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task, :style => "margin-top:30px") do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :deadline %><br>
    <%= f.datetime_select :deadline, {}, :class => "form-control date-select" %>
  </div>
  <div class="form-group">
    <%= f.label :assigned_name %><br>
    <%= f.text_field :assigned_name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :assigned_phone %><br>
    <%= f.text_field :assigned_phone, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :state %><br>
    <%= f.select :state, [['Pending','pending'],['Waiting for response','waiting_response'],['In conversation','conversation'],['Accepted','accepted'],['Rejected','rejected'],['Completed','completed']], :class => "form-control" %>
  </div>

  <%= f.submit "Save", :class => "btn btn-primary" %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit TASK <%= @task.id %></h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>Listing <%= pluralize(@tasks.count, "task") %></h1>

<table>
  <tr>
    <th>Id</th>
    <th>Deadline</th>
    <th>Assignee</th>
    <th>Phone</th>
    <th>State</th>
    <th>SMS state</th>
    <th>Last message</th>
    <th colspan="3"></th>
  </tr>

  <% @tasks.each do |task| %>
    <tr>
      <td><%= task.id %></td>
      <td><%= l(task.deadline, :format => :default) %></td>
      <td><%= task.assigned_name %></td>
      <td><%= task.assigned_phone %></td>
      <td><%= task.state %></td>
      <td><%= task.last_message_state %></td>
      <td><%= task.last_message ? task.last_message.gsub(/(\r)?\n/, "<br />").html_safe : "" %></td>
      <td>
        <%= link_to 'Show', task, :class => "btn" %>
        <%= link_to 'Edit', edit_task_path(task), :class => "btn" %>
        <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn" %>
        <%= link_to 'SMS', sms_task_path(task), :class => "btn" %>
      </td>
    </tr>
  <% end %>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<h1>Task <%= @task.id %></h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>Deadline:</strong>
  <%= @task.deadline %>
</p>

<p>
  <strong>Assigned name:</strong>
  <%= @task.assigned_name %>
</p>

<p>
  <strong>Assigned phone:</strong>
  <%= @task.assigned_phone %>
</p>

<p>
  <strong>State:</strong>
  <%= @task.state %>
</p>

<p>
  <strong>Last SMS:</strong>
  <%= @task.last_message ? @task.last_message.gsub(/(\r)?\n/, "<br />").html_safe : "" %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Empty log', empty_log_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

<br />
<br />
<br />

<h3>Task log</h3>
<table>
  <thead>
    <tr>
      <th>Time</th>
      <th>State</th>
      <th>SMS state</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @task.task_logs.each do |task_log| %>
      <tr>
        <td><%= l(task_log.created_at) %></td>
        <td><%= task_log.state %></td>
        <td><%= task_log.message_state %></td>
        <td><%= task_log.message ? task_log.message.gsub(/(\r)?\n/, "<br />").html_safe : "" %></td>
      </tr>
    <% end %>
  </tbody>
</table>